src/java/br/com/provacaed/entity/Aluno.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.provacaed.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author crist
 */
@Entity
@Table(name = "aluno")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Aluno.findAll", query = "SELECT a FROM Aluno a"),
    @NamedQuery(name = "Aluno.findById", query = "SELECT a FROM Aluno a WHERE a.id = :id"),
    @NamedQuery(name = "Aluno.findByNome", query = "SELECT a FROM Aluno a WHERE a.nome = :nome"),
    @NamedQuery(name = "Aluno.findByDataNascimento", query = "SELECT a FROM Aluno a WHERE a.dataNascimento = :dataNascimento"),
    @NamedQuery(name = "Aluno.findBySexo", query = "SELECT a FROM Aluno a WHERE a.sexo = :sexo")})
public class Aluno implements Serializable {



    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Integer id;
    @Basic(optional = false)
    @Column(name = "nome")
    private String nome;
    @Basic(optional = false)
    @Column(name = "dataNascimento")
    @Temporal(TemporalType.DATE)
    private Date dataNascimento;
    @Basic(optional = false)
    @Column(name = "sexo")
    private String sexo;

    public Aluno() {
    }

    public Aluno(Integer id) {
        this.id = id;
    }

    public Aluno(Integer id, String nome, Date dataNascimento, String sexo) {
        this.id = id;
        this.nome = nome;
        this.dataNascimento = dataNascimento;
        this.sexo = sexo;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public Date getDataNascimento() {
        return dataNascimento;
    }

    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    
    /**
     * Formatar Data 
     **/
    public String getDataNascimentoFormatada() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false);
        return sdf.format(this.getDataNascimento());
    }
    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Aluno)) {
            return false;
        }
        Aluno other = (Aluno) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "br.com.provacaed.entity.Aluno[ id=" + id + " ]";
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }
    
}

src/java/br/com/provacaed/Bean/AlunoMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.provacaed.Bean;

import br.com.provacaed.relatorio.Relatorio;
import br.com.provacaed.DAO.AlunoDAO;
import br.com.provacaed.entity.Aluno;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;


/**
 *
 * @author crist
 */

@ManagedBean(name = "alunoMB")
@ViewScoped
public class AlunoMB {
      
    private Aluno aluno;
    private List<Aluno> lista = new ArrayList<Aluno>();
    AlunoDAO dao;
    public Aluno getAluno() {
        return aluno;
    }

    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

    public List<Aluno> getLista() {
        return lista;
    }

    public void setLista(List<Aluno> lista) {
        this.lista = lista;
    }
    public void limpar(){
        aluno = new Aluno();
    }
    public void salvar(){
        dao = new AlunoDAO();
        if (aluno.getId() == null){
            dao.salvar(aluno);
        }else{
            dao.alterar(aluno);
        }

        inicializar();
    }
    public void deletar(Aluno item){
        dao = new AlunoDAO();
        dao.deletar(item.getId());
        inicializar();
    }
    public void carregarAluno(Aluno item){
        aluno = item;
    }
    public void gerarRelatorio(){
        Relatorio relatorio = new Relatorio();

        relatorio.getRelatorio(lista);
    }   
    @PostConstruct
    public void inicializar(){
        AlunoDAO dao = new AlunoDAO();
      
        
        lista = dao.listar();
        limpar();
    }
}

web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <title>Prova Caed</title>
    </h:head>
    <h:body>

        <h:form id="formCadastro">
            <p:panel header="Cadastro de Alunos">  
                <p:messages id="msgs" />
            <h:panelGroup id="display">
                <p:panelGrid columns="2" >

                    <p:outputLabel value="Nome" for="nome" />
                    <p:inputText id="nome" value="#{alunoMB.aluno.nome}" required="true" label="Nome" />
                    <p:outputLabel value="Sexo" for="sexo" />
                    
                    <h:selectOneRadio id="sexo" value="#{alunoMB.aluno.sexo}" required="true" label="Sexo"> 
                        <f:selectItem itemValue="M" itemLabel="Masculino"/>    
                        <f:selectItem itemValue="F" itemLabel="Feminino"/> 
                    </h:selectOneRadio>
                    <p:outputLabel value="Data de Nascimento" for="dtNasc" />
                    <p:calendar  id="dtNasc" value="#{alunoMB.aluno.dataNascimento}" required="true" label="Data de Nascimento" pattern="dd/MM/yyyy">
                    </p:calendar>   

                </p:panelGrid>
                <p:commandButton actionListener="#{alunoMB.salvar()}" value="Salvar" update="@form :formLista"/>
                <p:commandButton value="Cancelar" action="#{alunoMB.limpar}" update="@form" process="@this" />
            </h:panelGroup>
            </p:panel>
        </h:form>


        <h:form id="formLista">
            <p:panel header="Lista de Alunos">  
            <p:dataTable var="item" value="#{alunoMB.lista}" emptyMessage="Sem regstros">
                <p:column headerText="Código">
                    #{item.id}
                </p:column>
                <p:column  headerText="Nome" sortBy="#{item.nome}" filterBy="#{item.nome}" filterMatchMode="contains">
                    #{item.nome}
                </p:column>
                <p:column headerText="Data de Nacimento">
                    #{item.dataNascimentoFormatada}
                </p:column>     
                <p:column headerText="Ações">
                    <p:commandButton action="#{alunoMB.carregarAluno(item)}" value="Editar" update=":formCadastro" />
                    <p:commandButton action="#{alunoMB.deletar(item)}" value="Excluir" update="@form"/>
                </p:column> 
            </p:dataTable>

            <p:commandButton action="#{alunoMB.gerarRelatorio()}" ajax="false" value="Relatório" onclick="this.form.taget = '_blanck'" />
            </p:panel> 
        </h:form>

    </h:body>
</html>

web/welcomePrimefaces.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>PrimeFaces</title>
            </f:facet>
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="true" closable="true" collapsible="true">
                    Header
                </p:layoutUnit>

                <p:layoutUnit position="south" size="100" closable="true" collapsible="true">
                    Footer
                </p:layoutUnit>

                <p:layoutUnit position="west" size="175" header="Left" collapsible="true">
                    <p:menu>
                        <p:submenu label="Resources">
                            <p:menuitem value="Demo" url="http://www.primefaces.org/showcase-labs/ui/home.jsf" />
                            <p:menuitem value="Documentation" url="http://www.primefaces.org/documentation.html" />
                            <p:menuitem value="Forum" url="http://forum.primefaces.org/" />
                            <p:menuitem value="Themes" url="http://www.primefaces.org/themes.html" />

                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    Welcome to PrimeFaces
                </p:layoutUnit>

            </p:layout>

        </h:body>

    </f:view>
</html>